### ISSUE TITLE
Input file name collision occurs for fastp and falco

### ISSUE THREAD

**Issue by kkami1115** [nf-core/demultiplex#106]
### Description of the bug

When I ran a pipeline (v1.1.0), this error occurs at beginning of fastp transaction. 
```
ERROR ~ Error executing process > 'NFCORE_DEMULTIPLEX:DEMULTIPLEX:FASTP (7)'

Caused by:
  Process `NFCORE_DEMULTIPLEX:DEMULTIPLEX:FASTP` input file name collision -- There are multiple input files for each of the following file names:  [[NAMES OF fastq.gz]]
```
Also, on the Nextflow monitoring screen, the number of tasks assigned to Fastp is one less than the original number of samples, and it seems that two fastq.gz files are assigned to one sample and an error has occurred.

What should I do about this error? I am a beginner with Nextflow and don’t know how to debug it.

### System information

Nextflow version: version 23.04.1 build 5866
Hardware: HPC
Executor: local
Container engine: Singularity
OS: CentOS Linux
Version of nf-core/demultiplex: 1.1.0

**Comment by matthdsm** [comment]
Hi,
Are you able to share your samplesheet(s) and your `.nextflow.log`? 

M

**Comment by kamiyaky** [comment]
Hi Matthias, thanks for reply.
Unfortunately, sharing those two files look difficult.

I thought it's not the pipeline's fault, so I looked at the execution results and found that if fastq.gz already existed in the run folder, a file name collision occurred.
Probably, because the run folder is placed as a symbolic link in the work folder where bcl-convert is performed, it seems that collision occurs at `[ ! -f  ${prefix}.fastq.gz ] && ln -sf $reads ${prefix}.fastq.gz` in main.sf of Fastp or Falco.
So, is there a line somewhere recursively looking for  file names? Fixing that might solve the problem.

**Comment by kkami1115** [comment]
Hi Matthias, thanks for reply.
Unfortunately, sharing those two files look difficult.

I thought it's not the pipeline's fault, so I looked at the execution results and found that if fastq.gz already existed in the run folder, a file name collision occurred.
Probably, because the run folder is placed as a symbolic link in the work folder where bcl-convert is performed, it seems that collision occurs at `[ ! -f  ${prefix}.fastq.gz ] && ln -sf $reads ${prefix}.fastq.gz` in main.sf of Fastp or Falco.
So, is there a line somewhere recursively looking for file names? Fixing that might solve the problem.

**Comment by grst** [comment]
I would say it's rather uncommon (or at least bad practice) to have fastq files in the flowcell folder. The modification you suggest makes sense, I just see an issue with the pattern: When there are many samples, you could have `xx_S10_xxx` which wouldn't be matched by `[1-9]*`, so maybe `\d+` would be better.
