### ISSUE TITLE
[Question]: Upgrading bcl-convert to 4.2.4

### ISSUE THREAD

**Issue by tamuanand** [nf-core/demultiplex#150]
Hi @robsyme and @Emiller88 

I find that nf-core/demultiplex uses bcl-convert:4.0.3 - https://github.com/nf-core/modules/blob/master/modules/nf-core/bclconvert/main.nf#L5

Illumina has made lots of changes to bcl-convert 4.1.5 and in 4.2.4 (current version) 
- screenshot below from https://support.illumina.com/content/dam/illumina-support/documents/downloads/software/BCLConvert/v4/200040848_00_4.2.4_BCLConvert_Customer_Release_Notes.pdf

I think the pipeline should be updated to use 4.2.4 
- https://support.illumina.com/sequencing/sequencing_software/bcl-convert/downloads.html

![image](https://github.com/nf-core/demultiplex/assets/8467214/98cff86a-4e4a-4884-99b3-24a5a10c4879)

Thoughts?

**Comment by glichtenstein** [comment]
Hi @ tamuanand, @robsyme and @Emiller88, we are also in the need to upgrade `bcl-convert`, when running with new Illumina NovaSeq X+ data, bcl-convert 4.0.3 is erroring out on the indexes Hamming distance, which seems to be fixed in latest version 4.2.4 as we checked by processing with basespace's bcl-convert:
`Command error: ERROR: Sample Sheet Error: Insufficient hamming distance for 1-mismatch-tolerance between AGAAGGAT and AGAATGGTTT at common value AGA###### in i7 index of lane 8 ERROR: Sample Sheet Error: Insufficient hamming distance for 1-mismatch-tolerance between ACG##### and TCG###### at common value TCG####### in i7 index of lane 8`.

ref: [https://hub.docker.com/r/nfcore/bclconvert/tags](https://hub.docker.com/r/nfcore/bclconvert/tags)

Do you think it may be possible to upgrade it on your side? 
Please, let me know if there is anything I can do to help or contribute, maybe creating the Dockerfile, etc. 
Thank you very much!

**Comment by robsyme** [comment]
Hi all.
I've just requested @maxulysse to pull+push the new bcl-convert docker image up to the nf-core account. When this is uploaded, we can bump the module version.

**Comment by pilare** [comment]
Any chances for 1.4.0 release soon? Milestone 1.4.0 seems to be now complete.
https://github.com/nf-core/demultiplex/milestone/5
I see docker image for bclconvert 4.2.4 is still not in docker hub. @maxulysse we need help here.
https://hub.docker.com/r/nfcore/bclconvert/tags

**Comment by Emiller88** [comment]
The image is on quay https://quay.io/repository/nf-core/bclconvert?tab=tags

So I think dev should have 4.2.4 now?

> Any chances for 1.4.0 release soon? Milestone 1.4.0 seems to be now complete.

@pilare I try to just add things as we go to keep track of them more so. I probably won't have time until after the Summit to go through a release myself. 

Anyone is welcome to go through the release process themselves if you really want a tag on it! I'd love to review the PRs! [Docs for the process](https://nf-co.re/docs/contributing/release_checklist#before-you-release)

I also started added a team @nf-core/demultiplex! [Hit the join button here if you'd like to get involved](https://github.com/orgs/nf-core/teams/demultiplex) or ping me on slack!

**Comment by glichtenstein** [comment]
> The image is on quay https://quay.io/repository/nf-core/bclconvert?tab=tags
> 
> So I think dev should have 4.2.4 now?
> 
> > Any chances for 1.4.0 release soon? Milestone 1.4.0 seems to be now complete.
> 
> @pilare I try to just add things as we go to keep track of them more so. I probably won't have time until after the Summit to go through a release myself.
> 
> Anyone is welcome to go through the release process themselves if you really want a tag on it! I'd love to review the PRs! [Docs for the process](https://nf-co.re/docs/contributing/release_checklist#before-you-release)
> 
> I also started added a team @nf-core/demultiplex! [Hit the join button here if you'd like to get involved](https://github.com/orgs/nf-core/teams/demultiplex) or ping me on slack!

@Emiller88 Just to confirm, I have this question: Does the main.nf for bclconvert (https://github.com/nf-core/modules/blob/master/modules/nf-core/bclconvert/main.nf) calls for `container "nf-core/bclconvert:4.2.4"`
Will point to quay.io (https://quay.io/repository/nf-core/bclconvert?tab=tags)
or to dockerhub (https://hub.docker.com/r/nfcore/bclconvert/tags)? Thanks!
