### ISSUE TITLE
Samshee improvements

### ISSUE THREAD

**Issue by edmundmiller** [nf-core/demultiplex#237]
Is this stub running the same script?

That defeats the purpose of a stub, its should just pass, and I think the rest of it isn't necessary. It can even take in the same sample sheet and json, just don't run the validation.

_Originally posted by @edmundmiller in https://github.com/nf-core/demultiplex/pull/234#discussion_r1712050040_

- [ ] Make the stub simpler(Just pass the process and report the versions)
- [ ] [Improve the error handling to exit from Nextflow, not just crash the process, to crash the workflow.](https://github.com/nf-core/demultiplex/pull/234#discussion_r1710416307)

**Comment by nschcolnicov** [comment]
Hi @edmundmiller,
For the stub run I can modify it to be just:
```
stub:
    """
    cat <<-END_VERSIONS > versions.yml
    "${task.process}":
        samshee: \$( python -m pip show --version samshee | grep "Version" | sed -e "s/Version: //g" )
        python: \$( python --version | sed -e "s/Python //g" )
    END_VERSIONS
    """
```

About error handling, the script doesn't return an error exit status by itself, which is why I had to add the snippet for making it fail if it returned the "Validation failed" message.
I'm not sure what you mean by having it fail at a workflow level instead of a process level, does this mean to have the process return a value and then add a rule in the workflow to crash depending on the value that is returned by the process? If this is what you mean, what would be the advantage of having this vs having it fail at a process level?

**Comment by apeltzer** [comment]
My understanding here was, that the pipeline should fail immediately for this process if it fails. We could handle this also via the `modules.config` and setting the errorStrategy for samshee to something that https://www.nextflow.io/docs/latest/process.html#errorstrategy immediately fails such as `errorStrategy terminate` within the samshee process configuration. That should be feasible and make it fail the entire pipeline if it doesn't validate the samplesheet properly ✅
