### ISSUE TITLE
Remove confusing samplesheet language

### ISSUE THREAD

**Issue by edmundmiller** [nf-core/demultiplex#98]
### Description of the bug

The Demux tool "samplesheet" and the nf-core "samplesheet" are confusing to discuss. 

This is not to get rid of either, just to rename one of them. I'm biased towards Element's "RunManifest" instead of "samplesheet" but I acknowledge if we adopted that we'd probably confuse more people.

So changes to the nf-core "samplesheet" terminology is what I think the way forward is.

**Comment by sam-white04** [comment]
@Emiller88 how about "FlowcellMetadata"? 
Meaning, the command line would look like this:
```console
nextflow run demultiplex --input <FlowcellMetadata> --demultiplexer <demultiplexer>
```

**Comment by matthdsm** [comment]
I _think_ I made a point of naming the nf-core samplesheet as `flowcells.csv` to have a better distinction

**Comment by sam-white04** [comment]
I could have misunderstood but I think the usage docs refer to the input as a samplesheet (samplesheet.csv) https://github.com/nf-core/demultiplex/blob/master/docs/usage.md

**Comment by Emiller88** [comment]
🙈

**Comment by blajoie** [comment]
If the NF convention for a input-samplesheet is to use a `samplesheet.csv`, then my vote would be to leave that unchanged.  Keeping it consistent across various NF workflows.  

Documentation can be added to explain the Illumina centric nuance with reusing samplesheet.csv for two purposes.

**Comment by nh13** [comment]
I disagree with @blajoie.

The sample sheet describes samples and barcodes needed by a single demultiplexing invocation.  The input to this pipeline is a manifest of independent invocations of the demultiplexer, with each invocation having its own path to to a file containing information about the samples and barcodes to demultiplex.  These are fundamentally different concerns (the list of independent demux invocations vs. the sample metadata per invocation).

The name "sample sheet" is unfortunately/fortunately used to describe the per-sample metadata (name, id, barcode(s)) and is in wide spread use, so has an understood format and expected content.  It is super confusing to also use it as the "format" for this pipeline at the top level.

**Comment by nh13** [comment]
To be clear, here is the single metadata file that should be given as input to this pipeline: https://github.com/nf-core/demultiplex/blob/master/docs/usage.md#full-samplesheet
![Screen Shot 2023-03-07 at 1 42 03 PM](https://user-images.githubusercontent.com/846274/223547638-7c2ec4e8-bafe-4603-8c5a-7c8b25fa25a9.png)

Then in that file, there is a path to the sample sheet per flowcell that contains the information about the samples and barcodes.

The idea is to rename the top level file "full samplesheet" since it is not a sample sheet, and we don't want to overload that term.
